# 开发环境项目配置文件
sys:
  envType: dev
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_starter?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa.hibernate.ddl-auto: update #支持反向往数据库中添加内容
  jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext